#!/bin/bash
echo ============setting up docker container for swagger UI on localhost:8090============ &&
sudo docker run -p 8090:8080 -e API_URL=http://localhost:8080/v2/api-docs.json -d swaggerapi/swagger-ui
